### ISSUE TITLE
Any way to call actions in actions?

### ISSUE THREAD

**Issue by congjiujiu** [InfiniteXyy/zoov#10]
Like below

```typescript
const module = defineModule({}).actions({
  fnA() {},
  fnB() {
    // some way to call fnA
  }
}).methods({
  async fnC() {},
  async fnD() {
    // some way to call fnD
  }
})
.build()
```

And I try to use `module.getActions().fnA()`, but it has some unexpected failures [stackblitz](https://stackblitz.com/edit/vitejs-vite-jbkcjt?file=src%2Fbasic-usage%2Findex.tsx)
You can have look at the link above, if you click the `+1` button and see the console output, you will find a mistake with logs like this:

![CleanShot 2023-06-09 at 10 08 05@2x](https://github.com/InfiniteXyy/zoov/assets/7553572/95bb1c0d-93ec-40df-997e-c79fe346ff57)

**Comment by InfiniteXyy** [comment]
Hi 99, sadly, this is this is an expected behaviour, and can not be changed by design.
The action is implemented based on Immer, and changes on the draft object will not be directly updated to state.

**The state is changed only after this action closure ends**

The principle is always keep action simple, and compose them in methods
So the work around is like
```ts
const CounterModule = defineModule({ count: 0 })
  .actions({
    add(draft, payload: number = 1) {
      draft.count += payload;
      console.log("in add", draft.count)
    },
  })
  .methods({
    addAndLog(payload: number = 1) {
      this.getActions().add(payload); // when the action ends, state is updated
      console.info("in log: ", this.getState().count);
    },
  })
  .build();
```

**Comment by black7375** [comment]
Similar but different questions.
Is there a way to access `computed` from `actions` or `methods`?

```js
const CounterModule = defineModule({ count: 0 })
  .coumputed({ double: state => state.count * 2 })
  .methods(({ getComputed }) => ({ console.log( getComputed().double ); })) // Do something
  .build()
```

**Comment by InfiniteXyy** [comment]
> Similar but different questions. Is there a way to access `computed` from `actions` or `methods`?
> 
> ```js
> const CounterModule = defineModule({ count: 0 })
>   .coumputed({ double: state => state.count * 2 })
>   .methods(({ getComputed }) => ({ console.log( getComputed().double ); })) // Do something
>   .build()
> ```

This is not supported currently, but I think this is possible, I will try to add this feature

**Comment by InfiniteXyy** [comment]
> Similar but different questions. Is there a way to access `computed` from `actions` or `methods`?
> 
> ```js
> const CounterModule = defineModule({ count: 0 })
>   .coumputed({ double: state => state.count * 2 })
>   .methods(({ getComputed }) => ({ console.log( getComputed().double ); })) // Do something
>   .build()
> ```

This is supported in the latest version v0.5.6

**Comment by black7375** [comment]
Thank you for the quick update !!
