### ISSUE TITLE
Can't use in create-react-app due to mjs file

### ISSUE THREAD

**Issue by shaaandi** [InfiniteXyy/zoov#3]
I get the following error 

Failed to compile.

./node_modules/zoov/dist/index.mjs
Can't import the named export 'redux' from non EcmaScript module (only default export is available)

**Comment by InfiniteXyy** [comment]
Which version of react, zustand, react-scripts are you using?

It seems to work fine with the latest version of create-react-app.

**Comment by InfiniteXyy** [comment]
I refactor the export map, according to this post https://blog.axlight.com/posts/how-jotai-specifies-package-entry-points/, 

Does the issue still exist in zoov@0.3.0?

**Comment by shaaandi** [comment]
Sorry, I still have isssue but as it was NOT in your code sandbox so I close it here. We are using some different tooling on top of carco so that's why I close it here. 
I will investigate later and then update here. Many thanks.
